name: List packages
description: Output list of known packages

outputs:
  list:
    description: List of updated packages
    value: ${{ steps.list-generator.outputs.list }}

runs:
  using: composite
  steps:
    - name: Generate list
      id: list-generator
      shell: bash
      # Do not run command inside a $(...) clause, else errors won't be caught !
      run: |
        # Generate list
        ./vendor/bin/monorepo-builder packages:list --json > list.json
        cat list.json | jq
        echo "list=$(cat list.json)" >> $GITHUB_OUTPUT
