#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use PhpJsonRpc\Builder\Command as Commands;
use Symfony\Component\Console\Application;

$application = new Application('echo', '1.0.0');

$application->add(new Commands\ChangelogRequiredBumpCommand());

$application->run();
