<?php
declare(strict_types=1);

namespace PhpJsonRpc\Builder\VersionLock;

enum ShKeys: string
{
    case CURRENT = 'CURRENT_VERSION';
    case CURRENT_SHORT = 'CURRENT_VERSION_SHORT';
    case CURRENT_MAJOR_DIGIT = 'CURRENT_VERSION_MAJOR_DIGIT';
    case CURRENT_MINOR_DIGIT = 'CURRENT_VERSION_MINOR_DIGIT';
    case CURRENT_PATCH_DIGIT = 'CURRENT_VERSION_PATCH_DIGIT';
    case CURRENT_IS_STABLE = 'CURRENT_VERSION_IS_STABLE';
    case CURRENT_IS_FIRST_PATCH_OF_MINOR_VERSION = 'CURRENT_VERSION_IS_FIRST_PATCH_OF_MINOR_VERSION';
    case CURRENT_IS_FIRST_MINOR_OF_MAJOR_VERSION = 'CURRENT_VERSION_IS_FIRST_MINOR_OF_MAJOR_VERSION';
    case CURRENT_IS_FIRST_MAJOR_VERSION = 'CURRENT_VERSION_IS_FIRST_MAJOR_VERSION';
    case DEV_SUFFIX = 'DEV_SUFFIX';
    case NEXT_MAJOR = 'NEXT_MAJOR_VERSION';
    case NEXT_MAJOR_BRANCH_EXISTS = 'NEXT_MAJOR_VERSION_BRANCH_EXISTS';
    case NEXT_MAJOR_SHORT = 'NEXT_MAJOR_VERSION_SHORT';
    case NEXT_MAJOR_MAJOR_DIGIT = 'NEXT_MAJOR_VERSION_MAJOR_DIGIT';
    case NEXT_MAJOR_MINOR_DIGIT = 'NEXT_MAJOR_VERSION_MINOR_DIGIT';
    case NEXT_MAJOR_PATCH_DIGIT = 'NEXT_MAJOR_VERSION_PATCH_DIGIT';
    case NEXT_MINOR = 'NEXT_MINOR_VERSION';
    case NEXT_MINOR_BRANCH_EXISTS = 'NEXT_MINOR_VERSION_BRANCH_EXISTS';
    case NEXT_MINOR_SHORT = 'NEXT_MINOR_VERSION_SHORT';
    case NEXT_MINOR_MAJOR_DIGIT = 'NEXT_MINOR_VERSION_MAJOR_DIGIT';
    case NEXT_MINOR_MINOR_DIGIT = 'NEXT_MINOR_VERSION_MINOR_DIGIT';
    case NEXT_MINOR_PATCH_DIGIT = 'NEXT_MINOR_VERSION_PATCH_DIGIT';
    case NEXT_PATCH = 'NEXT_PATCH_VERSION';
    case NEXT_PATCH_BRANCH_EXISTS = 'NEXT_PATCH_VERSION_BRANCH_EXISTS';
    case NEXT_PATCH_SHORT = 'NEXT_PATCH_VERSION_SHORT';
    case NEXT_PATCH_MAJOR_DIGIT = 'NEXT_PATCH_VERSION_MAJOR_DIGIT';
    case NEXT_PATCH_MINOR_DIGIT = 'NEXT_PATCH_VERSION_MINOR_DIGIT';
    case NEXT_PATCH_PATCH_DIGIT = 'NEXT_PATCH_VERSION_PATCH_DIGIT';
    case NEXT_STABLE = 'NEXT_STABLE_VERSION';
    case NEXT_STABLE_BRANCH_EXISTS = 'NEXT_STABLE_VERSION_BRANCH_EXISTS';
    case NEXT_STABLE_SHORT = 'NEXT_STABLE_VERSION_SHORT';
    case NEXT_STABLE_MAJOR_DIGIT = 'NEXT_STABLE_VERSION_MAJOR_DIGIT';
    case NEXT_STABLE_MINOR_DIGIT = 'NEXT_STABLE_VERSION_MINOR_DIGIT';
    case NEXT_STABLE_PATCH_DIGIT = 'NEXT_STABLE_VERSION_PATCH_DIGIT';
}
