name: List packages
on:
  workflow_call:
    outputs:
      packages:
        description: List of packages
        value: ${{ jobs.packages.outputs.packages }}

permissions: {}

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.list-generator.outputs.list }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-php${{ steps.setup-php.outputs.php-version }}-${{ hashFiles('**/composer.lock') }}-list-packages

      - name: Install macrorepo
        run: make install

      - name: Generate list
        id: list-generator
        uses: ./.github/actions/list-packages
