name: List packages
on:
  workflow_call:
    inputs:
      state_from:
        description: 'Git base reference used to compute package state'
        type: string
        required: false
        default: ''
      state_from_remote:
        description: 'Git remote related to base reference'
        type: string
        required: false
        default: "originBase"
      state_from_remote_url:
        description: 'Git remote used related to base reference'
        type: string
        required: false
        default: "https://github.com/php-jsonrpc/poc-monorepo.git"
      updated_only:
        description: 'Weither or not to filter out non updated packages (requires `state_from` option !)'
        type: boolean
        required: false
        default: false
      split-branch-pattern:
        description: 'Split branch pattern'
        type: string
        required: false
    outputs:
      packages:
        description: List of packages
        value: ${{ jobs.main.outputs.packages }}
      updated_packages:
        description: List of updated package names
        value: ${{ jobs.main.outputs.updated_package_names }}

permissions: {}

jobs:
  main:
    name: Find${{ inputs.updated_only && ' updated' || '' }} known packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.list-generator.outputs.list }}
      updated_package_names: ${{ steps.updated-packages-list-generator.outputs.list }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create base git remote
        if: ${{ inputs.state_from }}
        run: |
            git remote add ${{ inputs.state_from_remote }} ${{ inputs.state_from_remote_url }}
            git fetch ${{ inputs.state_from_remote }} ${{ inputs.state_from }} --depth=1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            composer.lock
            vendor
          key: ${{ github.head_ref || github.ref }}-${{ hashFiles('**/composer.json') }}-list-packages-composer

      - name: Install macrorepo
        run: make install

      - name: Generate list
        id: list-generator
        shell: bash
        # Do not run command inside a $(...) clause, else errors won't be caught !
        run: |
          ./vendor/bin/monorepo-builder packages:list \
            --all-fields \
            ${{ inputs.state_from && format('--state-from=''{0}/{1}''', inputs.state_from_remote, inputs.state_from) || '' }} \
            ${{ inputs.updated_only && '--updated-only' || '' }} \
            ${{ inputs.split-branch-pattern && format('--split-branch-pattern=''{0}''', inputs.split-branch-pattern) || '' }} \
            --json | tee list.json 
          echo "list=$(cat list.json)" >> $GITHUB_OUTPUT

      - name: Generate updated packages list
        id: updated-packages-list-generator
        shell: bash
        # Do not run command inside a $(...) clause, else errors won't be caught !
        run: |
          echo '${{ steps.list-generator.outputs.list }}' | \
            jq -c -M 'map(select(.state == "updated")) | map(.name)' | \
            tee list.json 
          echo "list=$(cat list.json)" >> $GITHUB_OUTPUT
