name: List packages
on:
  workflow_call:
    inputs:
      split-branch-pattern:
        description: 'Split branch pattern to append for each package'
        type: string
        required: false
    outputs:
      packages:
        description: List of packages
        value: ${{ jobs.packages.outputs.packages }}
      updated_packages:
        description: List of updated package names
        value: ${{ jobs.packages.outputs.updated_package_names }}

permissions: {}

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ inputs.split-branch-pattern != '' && steps.list-with-split-branch-generator.outputs.list || steps.enhanced-list-generator.outputs.list }}
      updated_package_names: ${{ steps.updated-packages-list-generator.outputs.list }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            composer.lock
            vendor
          key: ${{ github.head_ref || github.ref_name }}-${{ hashFiles('**/composer.json') }}-list-packages-composer

      - name: Install macrorepo
        run: make install

      - name: Generate list
        id: list-generator
        uses: ./.github/actions/list-packages

      - name: Resolve packages state
        id: enhanced-list-generator
        uses: ./.github/actions/resolve-packages-state
        with:
          list: ${{ steps.list-generator.outputs.list }}

      - name: Append packages split branch
        id: list-with-split-branch-generator
        if: ${{ inputs.split-branch-pattern != '' }}
        shell: bash
        # Do not run command inside a $(...) clause, else errors won't be caught !
        run: |
          # Append packages split branch
          echo '${{ steps.enhanced-list-generator.outputs.list }}' | \
            jq -r -M 'map(. + { "split_branch": ${{ toJson(inputs.split-branch-pattern) }} } ) | tostring' \
            > list.json
          cat list.json | jq
          echo "list=$(cat list.json)" >> $GITHUB_OUTPUT

      - name: Generate updated packages list
        id: updated-packages-list-generator
        shell: bash
        # Do not run command inside a $(...) clause, else errors won't be caught !
        run: |
          # Generate updated packages list
          echo '${{ steps.enhanced-list-generator.outputs.list }}' | \
            jq -c -M 'map(select(.state == "updated")) | map(.name)' \
            > list.json
          cat list.json | jq
          echo "list=$(cat list.json)" >> $GITHUB_OUTPUT
