name: 'Package CI'
on:
  workflow_call: # Allows to run the workflow from another workflow
    inputs:
      path:
        description: 'Path to the package'
        type: string
        required: true
      skip:
        description: 'Path to the package'
        type: boolean
        required: true
        default: false
  workflow_dispatch: # Allows to run the workflow manually from the Actions tab
    inputs:
      path:
        description: 'Path to the package'
        type: string
        required: true
      skip:
        description: 'Path to the package'
        type: boolean
        required: true
        default: false

env:
  absolute_package_path: ${{ github.workspace }}/${{ inputs.path || '.' }}
  is_macrorepo: ${{ inputs.path != '' }}
  head_ref: ${{ github.head_ref || github.ref }}

defaults:
  run:
    shell: bash

jobs:
  static_checks:
    name: Static checks
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.absolute_package_path }}/composer.lock
            ${{ env.absolute_package_path }}/vendor
          key: CI-composer-${{ env.head_ref }}-${{ hashFiles(format('{0}/composer.json', env.absolute_package_path)) }}

      - name: Install
        working-directory: ${{ env.absolute_package_path }}
        run: make install

      - name: PHPStan
        working-directory: ${{ env.absolute_package_path }}
        run: make phpstan

      - name: ComposerRequireChecker
        uses: ./.github/actions/composer-require-checker
        with:
          path: ${{ env.absolute_package_path }}
          config_path: ${{ env.absolute_package_path }}/composer.json

  uts_fts:
    name: UTs & FTs
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.absolute_package_path }}/composer.lock
            ${{ env.absolute_package_path }}/vendor
          key: CI-composer-${{ env.head_ref }}-${{ hashFiles(format('{0}/**/composer.json', env.absolute_package_path)) }}

      - name: Install
        working-directory: ${{ env.absolute_package_path }}
        run: make install

      - name: Unit tests
        working-directory: ${{ env.absolute_package_path }}
        run: make test-unit

      - name: Functional tests
        working-directory: ${{ env.absolute_package_path }}
        run: make test-functional
