name: Push to package branches
on:
  push:
    branches: [ develop ]

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  head_ref: ${{ github.event.head_ref || github.head_ref || github.ref }}
  base_ref: ${{ github.event.base_ref || github.base_ref || github.ref }}


permissions: {}

jobs:
  find-packages:
    name: Metadata
    uses: ./.github/workflows/list-packages.yaml
    with:
      state_from: ${{ env.base_ref }}

  resolve-required-bump:
    name: Metadata
    needs: [find-packages]
    uses: ./.github/workflows/resolve-packages-required-bump.yaml
    with:
      packages: ${{ needs.find-packages.outputs.packages }}

  resolve-branches:
    name: Metadata
    uses: ./.github/workflows/resolve-package-branches.yaml
    with:
      state_from: ${{ env.base_ref }}

  push_to_maintenance_branches:
    name: Push ${{ matrix.pkg_name }} to ${{ matrix.maintenance_branch }}
    if: ${{ needs.metadata.outputs.updated_package_names != '[]' && needs.metadata.outputs.updated_package_names != '' }}
    needs: [ metadata ]
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        pkg_name: ${{ fromJson(needs.metadata.outputs.updated_package_names) }}
    uses: ./.github/workflows/php-package-CI.yaml
    with:
      path: ${{ fromJson(needs.metadata.outputs.packages)[matrix.pkg_name].path }}
