name: Update branch
on:
  workflow_call:
    inputs:
      target:
        description: 'Branch name to update with base branch'
        type: string
        required: true
      base:
        description: 'Branch name to merge into target branch'
        type: string
        required: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  main:
    name: ${{ inputs.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Initialize target branch
        run: |
          git fetch origin ${{ inputs.target }} && exit 0 # Exit early if branch already exists
          git fetch origin ${{ inputs.base }}
          git checkout --track remotes/origin/${{ inputs.base }} -b ${{ inputs.target }}
          git push origin ${{ inputs.target }}
          echo '> ℹ️ Branch `${{ inputs.target }}` created from `origin/${{ inputs.base }}` and synchronized with `origin`' >> $GITHUB_STEP_SUMMARY

      - name: Check out target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target }}

      - name: Update target branch
        run: |
          git fetch origin ${{ inputs.base }} # Re-fetch base branch due to refs removal from actions/checkout
          git fetch origin ${{ inputs.target }} # Re-fetch target branch to retrieve all refs
          git status
          git pull origin ${{ inputs.base }}
          git push origin ${{ inputs.target }}
          echo '✅ Branch `${{ inputs.base }}` merged into `${{ inputs.target }}` and synchronized with `origin`' >> $GITHUB_STEP_SUMMARY
