name: Update package develop branches

on:
  push:
    branches: [ develop ]

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: false # false => wait previous workflow execution before starting

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  metadata:
    name: Metadata
    uses: ./.github/workflows/list-packages.yaml

  main:
    name: ${{ matrix.name }}
    if: ${{ needs.metadata.outputs.packages != '[]' && needs.metadata.outputs.packages != '' }}
    needs: [ metadata ]
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.metadata.outputs.packages).* }}
    permissions:
      contents: write
    uses: ./.github/workflows/update-branch.yaml
    with:
      head: develop
      base: tmp-test-split/${{ matrix.name }}/develop
