name: Update package develop branches

on:
  push:
    branches:
      - develop
      - split/**/*

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: false # false => wait previous workflow execution before starting

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  metadata:
    name: Metadata
    uses: ./.github/workflows/list-packages.yaml
    with:
      resolve-branches: true

  main:
    name: ${{ matrix.name }}
    needs: [ metadata ]
    if: ${{ needs.metadata.outputs.packages != '[]' && needs.metadata.outputs.packages != '' }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.metadata.outputs.packages).* }}
    permissions:
      contents: write
    uses: ./.github/workflows/update-branch.yaml
    with:
      head: ${{ matrix.current_branch }}
      base: ${{ matrix.target_branch }}
