name: Update package develop branches
on:
  push:
    branches: [ develop ]

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  metadata:
    name: Metadata
    uses: ./.github/workflows/list-packages.yaml
    with:
      state_from: ${{ github.base_ref || github.ref_name }}
      split-branch-pattern: 'tmp-test-split/%1$s/develop'

  main:
    name: ${{ matrix.name }}
    if: ${{ needs.metadata.outputs.packages != '[]' && needs.metadata.outputs.packages != '' }}
    needs: [ metadata ]
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.metadata.outputs.packages).* }}
    permissions:
      contents: write
    uses: ./.github/workflows/update-branch.yaml
    with:
      base: develop
      target: ${{ matrix.split_branch }}
