name: Update branch

on:
  workflow_call:
    inputs:
      base:
        description: 'Branch name to update with head branch'
        type: string
        required: true
      head:
        description: 'Branch name to merge into base branch'
        type: string
        required: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  main:
    name: ${{ inputs.base }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out current branch
        uses: actions/checkout@v3

      - name: Base branch exists ?
        id: base-branch-check
        run: |
          git fetch origin ${{ inputs.base }} -v && EXISTS=1 || EXISTS=0
          echo "::debug ::Base branch exits: $(test $EXISTS -eq 1 && echo 'Yes' || echo 'No')"
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

      - name: Initialize target branch
        if: ${{ steps.base-branch-check.outputs.exists == 0 }}
        run: |
          git fetch origin ${{ inputs.head }} -v # Fetch base branch info
          git checkout --track origin/${{ inputs.head }} -b ${{ inputs.base }}
          git push origin ${{ inputs.base }}
          echo '✅ Branch `${{ inputs.base }}` created from `origin/${{ inputs.head }}` and synchronized with `origin`' >> $GITHUB_STEP_SUMMARY

      - name: Update target branch
        if: ${{ steps.base-branch-check.outputs.exists == 1 }}
        # Branches created by actions/checkout are shallow clones by default
        # => unshallow head branch in order to make `git pull` able to use fast-forward mode
        # (useful if current branch is the head branch)
        run: |
          git fetch origin ${{ inputs.head }} --unshallow -v
          git checkout ${{ inputs.base }} # Ensure we are on target branch
          git pull origin ${{ inputs.head }} --ff-only
          git push origin ${{ inputs.base }}
          echo '✅ Branch `${{ inputs.base }}` updated with `origin/${{ inputs.head }}` and synchronized with `origin`' >> $GITHUB_STEP_SUMMARY
