name: Validate GitHub config
on:
  pull_request:
    paths:
      - '**/.github/actions/**/action.yaml'
      - '**/.github/actions/**/action.yml'
      - '**/.github/workflows/**/*.yaml'
      - '**/.github/workflows/**/*.yml'
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.result }}
    steps:
      - name: Checkout ${{ matrix.pkg_name }}
        uses: actions/checkout@v3

      - name: Initialize cache directory
        run: |
          mkdir -p ${{ github.workspace }}/cache
          echo "{}" > ${{ github.workspace }}/cache/package-lock.json

      - name: Configure Node
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/cache/package-lock.json

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            actions:
              - added|modified: '**/.github/actions/**/action.yaml'
              - added|modified: '**/.github/actions/**/action.yml'
            workflows:
              - added|modified: '**/.github/workflows/**/*.yaml'
              - added|modified: '**/.github/workflows/**/*.yml'

      - name: Install validator
        if: ${{ steps.node.outputs.cache-hit != 'true' }}
        run: npm install -g pajv # Used on next job to perform the validation

      - name: Install required NodeJs libs
        run:  npm install yaml # Used below to generate the matrix

      - name: Prepare matrix
        id: matrix
        uses: actions/github-script@v6
        with:
          script: |
            const yaml = require('yaml');
            const fs = require('fs');
            async function getName(filepath) {
              const content = fs.readFileSync(filepath, 'utf8')
              const decoded = yaml.parse(content);
            
              return 'name' in decoded ? decoded.name : null;
            }
            const list = [];
            for (const item of JSON.parse('${{ steps.changes.outputs.workflows_files }}')) {
              list.push({
                file: item, 
                type: 'workflow', 
                name: await getName(item),
              });
            }
            for (const item of JSON.parse('${{ steps.changes.outputs.actions_files }}')) {
              list.push({
                file: item, 
                type: 'action', 
                name: await getName(item),
              });
            }

            return list;
  

  validate:
    name: "\"${{ matrix.name || matrix.file }}\" ${{ matrix.type }}"
    runs-on: ubuntu-latest
    needs: [ metadata ]
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.metadata.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize cache directory
        run: |
          mkdir -p ${{ github.workspace }}/cache
          echo "{}" > ${{ github.workspace }}/cache/package-lock.json

      - name: Setup cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/cache/github-action.json-schema.json
            ${{ github.workspace }}/cache/github-workflow.json-schema.json
            ${{ github.workspace }}/cache/draft-07.json-schema.json
          key: validate-github-action-config-schema-cache

      - name: Download JSON schemas
        if: ${{ steps.cache.outputs.cache-hit != 'true'}}
        run: |
          wget https://json.schemastore.org/github-action.json -O ${{ github.workspace }}/cache/github-action.json-schema.json
          wget https://json.schemastore.org/github-workflow.json -O ${{ github.workspace }}/cache/github-workflow.json-schema.json
          wget http://json-schema.org/draft-07/schema -O ${{ github.workspace }}/cache/draft-07.json-schema.json

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/cache/package-lock.json

      - name: Validate
        env:
          OUTPUT_FILE_PATH: ${{ github.workspace }}/cache/pajv.output
          ERRORS_FILE_PATH: ${{ github.workspace }}/cache/pajv.errors
        run: |
          ($(npm -g config get prefix)/bin/pajv test \
            --valid \
            --errors=line \
            --json-pointers \
            --extend-refs=true \
            -s ${{ github.workspace }}/cache/github-${{ matrix.type }}.json-schema.json \
            -r ${{ github.workspace }}/cache/draft-07.json-schema.json \
            -d ${{ matrix.file }} 2>&1 \
          || true) >$OUTPUT_FILE_PATH
          echo "::debug ::$(cat $OUTPUT_FILE_PATH)"
          if [[ "$(cat $OUTPUT_FILE_PATH | tail -n +2 | wc -l)" -gt 0 ]]; then
            cat $OUTPUT_FILE_PATH | tail -n +2 | jq -r --color-output ' map("\(.dataPath): \(.message) (\(.params.additionalProperty))") | unique | join("\n") ' >$ERRORS_FILE_PATH  2>&1
            while IFS= read -r line; do
              echo "::error file=${{ matrix.file }}::$line"
            done <<< "$(cat $ERRORS_FILE_PATH)"
            exit 2
          fi
